### ISSUE TITLE
Update dependence fiber to ~3.0.0 

### ISSUE THREAD

**Issue by henrywang** [webdriverio-boneyard/wdio-sync#133]
The wdio-mocha-framework cannot be installed on Node 10 environment, because it depends on wdio-sync, and wdio-sync has a dependence, fiber. The fiber 2.x doesn't provide prebuilt binaries for Node 10, but fiber 3.0.0 does. Could you please update fiber on dependence from 2.x to 3.0.0. Thanks.

**Comment by christian-bromann** [comment]
> Could you please update fiber on dependence from 2.x to 3.0.0.

Feel free to propose a PR

**Comment by henrywang** [comment]
Issue got fixed on PR #134 and PR got merged.
