### ISSUE TITLE
Update fibers dependency to support node 12

### ISSUE THREAD

**Issue by pathmapper** [webdriverio-boneyard/wdio-sync#135]
Fibers `4.0.1` is available: https://www.npmjs.com/package/fibers

**Comment by rubenlg** [comment]
When do you plan to push a new version to npm with that dependency?

**Comment by knolleary** [comment]
Sorry to +1 on a closed issue, but we're trying to add Node 12 support to our project which uses this module in its testing and we're currently blocked by this.
